/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as AtletaIndexRouteImport } from './routes/atleta.index'
import { Route as AtletaWellnessRouteImport } from './routes/atleta.wellness'
import { Route as AtletaRpeRouteImport } from './routes/atleta.rpe'
import { Route as AtletaPerfilRouteImport } from './routes/atleta.perfil'
import { Route as CoachAtletaIdRouteImport } from './routes/coach.atleta.$id'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaIndexRoute = AtletaIndexRouteImport.update({
  id: '/atleta/',
  path: '/atleta/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaWellnessRoute = AtletaWellnessRouteImport.update({
  id: '/atleta/wellness',
  path: '/atleta/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaRpeRoute = AtletaRpeRouteImport.update({
  id: '/atleta/rpe',
  path: '/atleta/rpe',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaPerfilRoute = AtletaPerfilRouteImport.update({
  id: '/atleta/perfil',
  path: '/atleta/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachAtletaIdRoute = CoachAtletaIdRouteImport.update({
  id: '/coach/atleta/$id',
  path: '/coach/atleta/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/atleta/perfil': typeof AtletaPerfilRoute
  '/atleta/rpe': typeof AtletaRpeRoute
  '/atleta/wellness': typeof AtletaWellnessRoute
  '/atleta/': typeof AtletaIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/atleta/$id': typeof CoachAtletaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/atleta/perfil': typeof AtletaPerfilRoute
  '/atleta/rpe': typeof AtletaRpeRoute
  '/atleta/wellness': typeof AtletaWellnessRoute
  '/atleta': typeof AtletaIndexRoute
  '/coach': typeof CoachIndexRoute
  '/coach/atleta/$id': typeof CoachAtletaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/atleta/perfil': typeof AtletaPerfilRoute
  '/atleta/rpe': typeof AtletaRpeRoute
  '/atleta/wellness': typeof AtletaWellnessRoute
  '/atleta/': typeof AtletaIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/atleta/$id': typeof CoachAtletaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/registro'
    | '/atleta/perfil'
    | '/atleta/rpe'
    | '/atleta/wellness'
    | '/atleta/'
    | '/coach/'
    | '/coach/atleta/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/registro'
    | '/atleta/perfil'
    | '/atleta/rpe'
    | '/atleta/wellness'
    | '/atleta'
    | '/coach'
    | '/coach/atleta/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/registro'
    | '/atleta/perfil'
    | '/atleta/rpe'
    | '/atleta/wellness'
    | '/atleta/'
    | '/coach/'
    | '/coach/atleta/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  AtletaPerfilRoute: typeof AtletaPerfilRoute
  AtletaRpeRoute: typeof AtletaRpeRoute
  AtletaWellnessRoute: typeof AtletaWellnessRoute
  AtletaIndexRoute: typeof AtletaIndexRoute
  CoachIndexRoute: typeof CoachIndexRoute
  CoachAtletaIdRoute: typeof CoachAtletaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/': {
      id: '/atleta/'
      path: '/atleta'
      fullPath: '/atleta/'
      preLoaderRoute: typeof AtletaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/wellness': {
      id: '/atleta/wellness'
      path: '/atleta/wellness'
      fullPath: '/atleta/wellness'
      preLoaderRoute: typeof AtletaWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/rpe': {
      id: '/atleta/rpe'
      path: '/atleta/rpe'
      fullPath: '/atleta/rpe'
      preLoaderRoute: typeof AtletaRpeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/perfil': {
      id: '/atleta/perfil'
      path: '/atleta/perfil'
      fullPath: '/atleta/perfil'
      preLoaderRoute: typeof AtletaPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/atleta/$id': {
      id: '/coach/atleta/$id'
      path: '/coach/atleta/$id'
      fullPath: '/coach/atleta/$id'
      preLoaderRoute: typeof CoachAtletaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  AtletaPerfilRoute: AtletaPerfilRoute,
  AtletaRpeRoute: AtletaRpeRoute,
  AtletaWellnessRoute: AtletaWellnessRoute,
  AtletaIndexRoute: AtletaIndexRoute,
  CoachIndexRoute: CoachIndexRoute,
  CoachAtletaIdRoute: CoachAtletaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
