/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as AtletaIndexRouteImport } from './routes/atleta.index'
import { Route as CoachUsuariosRouteImport } from './routes/coach.usuarios'
import { Route as CoachSemaforoRouteImport } from './routes/coach.semaforo'
import { Route as CoachRecuperacionRouteImport } from './routes/coach.recuperacion'
import { Route as CoachPartidosRouteImport } from './routes/coach.partidos'
import { Route as CoachNotificacionesRouteImport } from './routes/coach.notificaciones'
import { Route as CoachJugadoresRouteImport } from './routes/coach.jugadores'
import { Route as CoachGymRouteImport } from './routes/coach.gym'
import { Route as CoachFisioRouteImport } from './routes/coach.fisio'
import { Route as CoachCuestionariosRouteImport } from './routes/coach.cuestionarios'
import { Route as CoachCoachesRouteImport } from './routes/coach.coaches'
import { Route as CoachCalendarioRouteImport } from './routes/coach.calendario'
import { Route as CoachBibliotecaRouteImport } from './routes/coach.biblioteca'
import { Route as AtletaWellnessRouteImport } from './routes/atleta.wellness'
import { Route as AtletaRpeRouteImport } from './routes/atleta.rpe'
import { Route as AtletaRecuperacionRouteImport } from './routes/atleta.recuperacion'
import { Route as AtletaPerfilRouteImport } from './routes/atleta.perfil'
import { Route as AtletaOnboardingRouteImport } from './routes/atleta.onboarding'
import { Route as AtletaGymRouteImport } from './routes/atleta.gym'
import { Route as AtletaFisioRouteImport } from './routes/atleta.fisio'
import { Route as AtletaCalendarioRouteImport } from './routes/atleta.calendario'
import { Route as AtletaBibliotecaRouteImport } from './routes/atleta.biblioteca'
import { Route as CoachAtletaIdRouteImport } from './routes/coach.atleta.$id'
import { Route as ApiPublicHooksPushRemindersRouteImport } from './routes/api/public/hooks/push-reminders'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaIndexRoute = AtletaIndexRouteImport.update({
  id: '/atleta/',
  path: '/atleta/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachUsuariosRoute = CoachUsuariosRouteImport.update({
  id: '/coach/usuarios',
  path: '/coach/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachSemaforoRoute = CoachSemaforoRouteImport.update({
  id: '/coach/semaforo',
  path: '/coach/semaforo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRecuperacionRoute = CoachRecuperacionRouteImport.update({
  id: '/coach/recuperacion',
  path: '/coach/recuperacion',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachPartidosRoute = CoachPartidosRouteImport.update({
  id: '/coach/partidos',
  path: '/coach/partidos',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachNotificacionesRoute = CoachNotificacionesRouteImport.update({
  id: '/coach/notificaciones',
  path: '/coach/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachJugadoresRoute = CoachJugadoresRouteImport.update({
  id: '/coach/jugadores',
  path: '/coach/jugadores',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachGymRoute = CoachGymRouteImport.update({
  id: '/coach/gym',
  path: '/coach/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachFisioRoute = CoachFisioRouteImport.update({
  id: '/coach/fisio',
  path: '/coach/fisio',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachCuestionariosRoute = CoachCuestionariosRouteImport.update({
  id: '/coach/cuestionarios',
  path: '/coach/cuestionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachCoachesRoute = CoachCoachesRouteImport.update({
  id: '/coach/coaches',
  path: '/coach/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachCalendarioRoute = CoachCalendarioRouteImport.update({
  id: '/coach/calendario',
  path: '/coach/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachBibliotecaRoute = CoachBibliotecaRouteImport.update({
  id: '/coach/biblioteca',
  path: '/coach/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaWellnessRoute = AtletaWellnessRouteImport.update({
  id: '/atleta/wellness',
  path: '/atleta/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaRpeRoute = AtletaRpeRouteImport.update({
  id: '/atleta/rpe',
  path: '/atleta/rpe',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaRecuperacionRoute = AtletaRecuperacionRouteImport.update({
  id: '/atleta/recuperacion',
  path: '/atleta/recuperacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaPerfilRoute = AtletaPerfilRouteImport.update({
  id: '/atleta/perfil',
  path: '/atleta/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaOnboardingRoute = AtletaOnboardingRouteImport.update({
  id: '/atleta/onboarding',
  path: '/atleta/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaGymRoute = AtletaGymRouteImport.update({
  id: '/atleta/gym',
  path: '/atleta/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaFisioRoute = AtletaFisioRouteImport.update({
  id: '/atleta/fisio',
  path: '/atleta/fisio',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaCalendarioRoute = AtletaCalendarioRouteImport.update({
  id: '/atleta/calendario',
  path: '/atleta/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaBibliotecaRoute = AtletaBibliotecaRouteImport.update({
  id: '/atleta/biblioteca',
  path: '/atleta/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachAtletaIdRoute = CoachAtletaIdRouteImport.update({
  id: '/coach/atleta/$id',
  path: '/coach/atleta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPushRemindersRoute =
  ApiPublicHooksPushRemindersRouteImport.update({
    id: '/api/public/hooks/push-reminders',
    path: '/api/public/hooks/push-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atleta/biblioteca': typeof AtletaBibliotecaRoute
  '/atleta/calendario': typeof AtletaCalendarioRoute
  '/atleta/fisio': typeof AtletaFisioRoute
  '/atleta/gym': typeof AtletaGymRoute
  '/atleta/onboarding': typeof AtletaOnboardingRoute
  '/atleta/perfil': typeof AtletaPerfilRoute
  '/atleta/recuperacion': typeof AtletaRecuperacionRoute
  '/atleta/rpe': typeof AtletaRpeRoute
  '/atleta/wellness': typeof AtletaWellnessRoute
  '/coach/biblioteca': typeof CoachBibliotecaRoute
  '/coach/calendario': typeof CoachCalendarioRoute
  '/coach/coaches': typeof CoachCoachesRoute
  '/coach/cuestionarios': typeof CoachCuestionariosRoute
  '/coach/fisio': typeof CoachFisioRoute
  '/coach/gym': typeof CoachGymRoute
  '/coach/jugadores': typeof CoachJugadoresRoute
  '/coach/notificaciones': typeof CoachNotificacionesRoute
  '/coach/partidos': typeof CoachPartidosRoute
  '/coach/recuperacion': typeof CoachRecuperacionRoute
  '/coach/semaforo': typeof CoachSemaforoRoute
  '/coach/usuarios': typeof CoachUsuariosRoute
  '/atleta/': typeof AtletaIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/atleta/$id': typeof CoachAtletaIdRoute
  '/api/public/hooks/push-reminders': typeof ApiPublicHooksPushRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atleta/biblioteca': typeof AtletaBibliotecaRoute
  '/atleta/calendario': typeof AtletaCalendarioRoute
  '/atleta/fisio': typeof AtletaFisioRoute
  '/atleta/gym': typeof AtletaGymRoute
  '/atleta/onboarding': typeof AtletaOnboardingRoute
  '/atleta/perfil': typeof AtletaPerfilRoute
  '/atleta/recuperacion': typeof AtletaRecuperacionRoute
  '/atleta/rpe': typeof AtletaRpeRoute
  '/atleta/wellness': typeof AtletaWellnessRoute
  '/coach/biblioteca': typeof CoachBibliotecaRoute
  '/coach/calendario': typeof CoachCalendarioRoute
  '/coach/coaches': typeof CoachCoachesRoute
  '/coach/cuestionarios': typeof CoachCuestionariosRoute
  '/coach/fisio': typeof CoachFisioRoute
  '/coach/gym': typeof CoachGymRoute
  '/coach/jugadores': typeof CoachJugadoresRoute
  '/coach/notificaciones': typeof CoachNotificacionesRoute
  '/coach/partidos': typeof CoachPartidosRoute
  '/coach/recuperacion': typeof CoachRecuperacionRoute
  '/coach/semaforo': typeof CoachSemaforoRoute
  '/coach/usuarios': typeof CoachUsuariosRoute
  '/atleta': typeof AtletaIndexRoute
  '/coach': typeof CoachIndexRoute
  '/coach/atleta/$id': typeof CoachAtletaIdRoute
  '/api/public/hooks/push-reminders': typeof ApiPublicHooksPushRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atleta/biblioteca': typeof AtletaBibliotecaRoute
  '/atleta/calendario': typeof AtletaCalendarioRoute
  '/atleta/fisio': typeof AtletaFisioRoute
  '/atleta/gym': typeof AtletaGymRoute
  '/atleta/onboarding': typeof AtletaOnboardingRoute
  '/atleta/perfil': typeof AtletaPerfilRoute
  '/atleta/recuperacion': typeof AtletaRecuperacionRoute
  '/atleta/rpe': typeof AtletaRpeRoute
  '/atleta/wellness': typeof AtletaWellnessRoute
  '/coach/biblioteca': typeof CoachBibliotecaRoute
  '/coach/calendario': typeof CoachCalendarioRoute
  '/coach/coaches': typeof CoachCoachesRoute
  '/coach/cuestionarios': typeof CoachCuestionariosRoute
  '/coach/fisio': typeof CoachFisioRoute
  '/coach/gym': typeof CoachGymRoute
  '/coach/jugadores': typeof CoachJugadoresRoute
  '/coach/notificaciones': typeof CoachNotificacionesRoute
  '/coach/partidos': typeof CoachPartidosRoute
  '/coach/recuperacion': typeof CoachRecuperacionRoute
  '/coach/semaforo': typeof CoachSemaforoRoute
  '/coach/usuarios': typeof CoachUsuariosRoute
  '/atleta/': typeof AtletaIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/atleta/$id': typeof CoachAtletaIdRoute
  '/api/public/hooks/push-reminders': typeof ApiPublicHooksPushRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recuperar'
    | '/registro'
    | '/reset-password'
    | '/atleta/biblioteca'
    | '/atleta/calendario'
    | '/atleta/fisio'
    | '/atleta/gym'
    | '/atleta/onboarding'
    | '/atleta/perfil'
    | '/atleta/recuperacion'
    | '/atleta/rpe'
    | '/atleta/wellness'
    | '/coach/biblioteca'
    | '/coach/calendario'
    | '/coach/coaches'
    | '/coach/cuestionarios'
    | '/coach/fisio'
    | '/coach/gym'
    | '/coach/jugadores'
    | '/coach/notificaciones'
    | '/coach/partidos'
    | '/coach/recuperacion'
    | '/coach/semaforo'
    | '/coach/usuarios'
    | '/atleta/'
    | '/coach/'
    | '/coach/atleta/$id'
    | '/api/public/hooks/push-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recuperar'
    | '/registro'
    | '/reset-password'
    | '/atleta/biblioteca'
    | '/atleta/calendario'
    | '/atleta/fisio'
    | '/atleta/gym'
    | '/atleta/onboarding'
    | '/atleta/perfil'
    | '/atleta/recuperacion'
    | '/atleta/rpe'
    | '/atleta/wellness'
    | '/coach/biblioteca'
    | '/coach/calendario'
    | '/coach/coaches'
    | '/coach/cuestionarios'
    | '/coach/fisio'
    | '/coach/gym'
    | '/coach/jugadores'
    | '/coach/notificaciones'
    | '/coach/partidos'
    | '/coach/recuperacion'
    | '/coach/semaforo'
    | '/coach/usuarios'
    | '/atleta'
    | '/coach'
    | '/coach/atleta/$id'
    | '/api/public/hooks/push-reminders'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/recuperar'
    | '/registro'
    | '/reset-password'
    | '/atleta/biblioteca'
    | '/atleta/calendario'
    | '/atleta/fisio'
    | '/atleta/gym'
    | '/atleta/onboarding'
    | '/atleta/perfil'
    | '/atleta/recuperacion'
    | '/atleta/rpe'
    | '/atleta/wellness'
    | '/coach/biblioteca'
    | '/coach/calendario'
    | '/coach/coaches'
    | '/coach/cuestionarios'
    | '/coach/fisio'
    | '/coach/gym'
    | '/coach/jugadores'
    | '/coach/notificaciones'
    | '/coach/partidos'
    | '/coach/recuperacion'
    | '/coach/semaforo'
    | '/coach/usuarios'
    | '/atleta/'
    | '/coach/'
    | '/coach/atleta/$id'
    | '/api/public/hooks/push-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AtletaBibliotecaRoute: typeof AtletaBibliotecaRoute
  AtletaCalendarioRoute: typeof AtletaCalendarioRoute
  AtletaFisioRoute: typeof AtletaFisioRoute
  AtletaGymRoute: typeof AtletaGymRoute
  AtletaOnboardingRoute: typeof AtletaOnboardingRoute
  AtletaPerfilRoute: typeof AtletaPerfilRoute
  AtletaRecuperacionRoute: typeof AtletaRecuperacionRoute
  AtletaRpeRoute: typeof AtletaRpeRoute
  AtletaWellnessRoute: typeof AtletaWellnessRoute
  CoachBibliotecaRoute: typeof CoachBibliotecaRoute
  CoachCalendarioRoute: typeof CoachCalendarioRoute
  CoachCoachesRoute: typeof CoachCoachesRoute
  CoachCuestionariosRoute: typeof CoachCuestionariosRoute
  CoachFisioRoute: typeof CoachFisioRoute
  CoachGymRoute: typeof CoachGymRoute
  CoachJugadoresRoute: typeof CoachJugadoresRoute
  CoachNotificacionesRoute: typeof CoachNotificacionesRoute
  CoachPartidosRoute: typeof CoachPartidosRoute
  CoachRecuperacionRoute: typeof CoachRecuperacionRoute
  CoachSemaforoRoute: typeof CoachSemaforoRoute
  CoachUsuariosRoute: typeof CoachUsuariosRoute
  AtletaIndexRoute: typeof AtletaIndexRoute
  CoachIndexRoute: typeof CoachIndexRoute
  CoachAtletaIdRoute: typeof CoachAtletaIdRoute
  ApiPublicHooksPushRemindersRoute: typeof ApiPublicHooksPushRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/': {
      id: '/atleta/'
      path: '/atleta'
      fullPath: '/atleta/'
      preLoaderRoute: typeof AtletaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/usuarios': {
      id: '/coach/usuarios'
      path: '/coach/usuarios'
      fullPath: '/coach/usuarios'
      preLoaderRoute: typeof CoachUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/semaforo': {
      id: '/coach/semaforo'
      path: '/coach/semaforo'
      fullPath: '/coach/semaforo'
      preLoaderRoute: typeof CoachSemaforoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/recuperacion': {
      id: '/coach/recuperacion'
      path: '/coach/recuperacion'
      fullPath: '/coach/recuperacion'
      preLoaderRoute: typeof CoachRecuperacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/partidos': {
      id: '/coach/partidos'
      path: '/coach/partidos'
      fullPath: '/coach/partidos'
      preLoaderRoute: typeof CoachPartidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/notificaciones': {
      id: '/coach/notificaciones'
      path: '/coach/notificaciones'
      fullPath: '/coach/notificaciones'
      preLoaderRoute: typeof CoachNotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/jugadores': {
      id: '/coach/jugadores'
      path: '/coach/jugadores'
      fullPath: '/coach/jugadores'
      preLoaderRoute: typeof CoachJugadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/gym': {
      id: '/coach/gym'
      path: '/coach/gym'
      fullPath: '/coach/gym'
      preLoaderRoute: typeof CoachGymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/fisio': {
      id: '/coach/fisio'
      path: '/coach/fisio'
      fullPath: '/coach/fisio'
      preLoaderRoute: typeof CoachFisioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/cuestionarios': {
      id: '/coach/cuestionarios'
      path: '/coach/cuestionarios'
      fullPath: '/coach/cuestionarios'
      preLoaderRoute: typeof CoachCuestionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/coaches': {
      id: '/coach/coaches'
      path: '/coach/coaches'
      fullPath: '/coach/coaches'
      preLoaderRoute: typeof CoachCoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/calendario': {
      id: '/coach/calendario'
      path: '/coach/calendario'
      fullPath: '/coach/calendario'
      preLoaderRoute: typeof CoachCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/biblioteca': {
      id: '/coach/biblioteca'
      path: '/coach/biblioteca'
      fullPath: '/coach/biblioteca'
      preLoaderRoute: typeof CoachBibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/wellness': {
      id: '/atleta/wellness'
      path: '/atleta/wellness'
      fullPath: '/atleta/wellness'
      preLoaderRoute: typeof AtletaWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/rpe': {
      id: '/atleta/rpe'
      path: '/atleta/rpe'
      fullPath: '/atleta/rpe'
      preLoaderRoute: typeof AtletaRpeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/recuperacion': {
      id: '/atleta/recuperacion'
      path: '/atleta/recuperacion'
      fullPath: '/atleta/recuperacion'
      preLoaderRoute: typeof AtletaRecuperacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/perfil': {
      id: '/atleta/perfil'
      path: '/atleta/perfil'
      fullPath: '/atleta/perfil'
      preLoaderRoute: typeof AtletaPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/onboarding': {
      id: '/atleta/onboarding'
      path: '/atleta/onboarding'
      fullPath: '/atleta/onboarding'
      preLoaderRoute: typeof AtletaOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/gym': {
      id: '/atleta/gym'
      path: '/atleta/gym'
      fullPath: '/atleta/gym'
      preLoaderRoute: typeof AtletaGymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/fisio': {
      id: '/atleta/fisio'
      path: '/atleta/fisio'
      fullPath: '/atleta/fisio'
      preLoaderRoute: typeof AtletaFisioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/calendario': {
      id: '/atleta/calendario'
      path: '/atleta/calendario'
      fullPath: '/atleta/calendario'
      preLoaderRoute: typeof AtletaCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/biblioteca': {
      id: '/atleta/biblioteca'
      path: '/atleta/biblioteca'
      fullPath: '/atleta/biblioteca'
      preLoaderRoute: typeof AtletaBibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/atleta/$id': {
      id: '/coach/atleta/$id'
      path: '/coach/atleta/$id'
      fullPath: '/coach/atleta/$id'
      preLoaderRoute: typeof CoachAtletaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/push-reminders': {
      id: '/api/public/hooks/push-reminders'
      path: '/api/public/hooks/push-reminders'
      fullPath: '/api/public/hooks/push-reminders'
      preLoaderRoute: typeof ApiPublicHooksPushRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AtletaBibliotecaRoute: AtletaBibliotecaRoute,
  AtletaCalendarioRoute: AtletaCalendarioRoute,
  AtletaFisioRoute: AtletaFisioRoute,
  AtletaGymRoute: AtletaGymRoute,
  AtletaOnboardingRoute: AtletaOnboardingRoute,
  AtletaPerfilRoute: AtletaPerfilRoute,
  AtletaRecuperacionRoute: AtletaRecuperacionRoute,
  AtletaRpeRoute: AtletaRpeRoute,
  AtletaWellnessRoute: AtletaWellnessRoute,
  CoachBibliotecaRoute: CoachBibliotecaRoute,
  CoachCalendarioRoute: CoachCalendarioRoute,
  CoachCoachesRoute: CoachCoachesRoute,
  CoachCuestionariosRoute: CoachCuestionariosRoute,
  CoachFisioRoute: CoachFisioRoute,
  CoachGymRoute: CoachGymRoute,
  CoachJugadoresRoute: CoachJugadoresRoute,
  CoachNotificacionesRoute: CoachNotificacionesRoute,
  CoachPartidosRoute: CoachPartidosRoute,
  CoachRecuperacionRoute: CoachRecuperacionRoute,
  CoachSemaforoRoute: CoachSemaforoRoute,
  CoachUsuariosRoute: CoachUsuariosRoute,
  AtletaIndexRoute: AtletaIndexRoute,
  CoachIndexRoute: CoachIndexRoute,
  CoachAtletaIdRoute: CoachAtletaIdRoute,
  ApiPublicHooksPushRemindersRoute: ApiPublicHooksPushRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
